earthlab/abc-classroom

- grading/__main__.py
This will print a nice message when the template repository already exists instead of crashing.
Closes #15
> Add handling of the case when the template repo exists

- abcclassroom/__main__.py
- abcclassroom/notebook.py
When placing a notebook in the student directory we inspect the kernel
name and re-write names like "Python [conda env:earth-analytics-python]"
to "Python 3". Conda env specific kernels might not be installed on the
student's computers or might have a different name there. This leaves
the instructors notebooks untouched.
For example a notebook like https://github.com/earth-analytics-edu/ea-spring-2019-lwasser/blob/master/week-06/time-series-homework-wk-6.ipynb will be changed when you run `abc-author` into a notebook that has a kernel called "Python 3".
Closes #20 and closes #48
> Normalise notebook kernel names

- MANIFEST.in
- abcclassroom/__main__.py
Looks like we missed a few cases when we changed the name in  #45
> change refs from grading to abcclassroom

- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- README.md
- dev-requirements.txt
- environment.yml
I am going to start chipping away at the package structure setting up things like 
* testing infrastructure
* docs and testing infrastructure
* dev environment
* etc
This pr includes
we also will want to push this to conda forge but there is no rush on this. having bumpversion in place however will be ideal for this workflow.
> dev setup instructions

- .gitignore
- CHANGELOG.md
this PR addresses #97 
a small edit to the gitignore to ignore the build dir where the initial pypi release files live was also added! e
> Add changelog to abc-classroom

- .travis.yml
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- dev-requirements.txt
- docs/change-log.rst
- docs/code-of-conduct.rst
- docs/conf.py
- docs/index.rst
* add m2r to build to support md docs
* add code of conduct to RTD
* update gitignore 
* remove python 3.5 build from travis
this addresses #96  and #97
> Update docs with code-of-conduct / change log, remove python 3.5 from travis

- CHANGELOG.md
- abcclassroom/config.py
- abcclassroom/example-data/config.yml
- abcclassroom/quickstart.py
- abcclassroom/template.py
- abcclassroom/tests/conftest.py
- abcclassroom/tests/test_assignment_template.py
- abcclassroom/tests/test_config.py
- docs/new_assignment.rst
Addresses #137 and #138. 
* abc-classroom will no longer modify the assignment name provided by adding the coursename as a prefix. 
* Name of each assignment gets added to an `assignments` section of the config. 
* Removed coursename and short_coursename from config because these are no longer used. 
* Added tests for assignment template scripts, as well as config functions
* Made some progress at more explicit handling of paths (a.k.a. where is my config file?)
> Assignment management

- abcclassroom/__main__.py
- abcclassroom/clone.py
- abcclassroom/example-data/config.yml
- abcclassroom/feedback.py
- abcclassroom/quickstart.py
- abcclassroom/template.py
- abcclassroom/tests/conftest.py
- abcclassroom/tests/test_assignment_template.py
- abcclassroom/tests/test_clone.py
- docs/get-started.rst
- docs/new_assignment.rst
Addresses #133 
We still assume / create most of the nbgrader directory structure under the course_materials directory, but no longer call this 'nbgrader' in the config, the code, or the docs. 
PR #147 should be merged first.
> Use generic course_materials instead of nbgrader

- abcclassroom/quickstart.py
- abcclassroom/tests/conftest.py
- abcclassroom/tests/test_quickstart.py
We changed the name of some of the config options, which was causing the quickstart tests to fail. This PR also modifies the quickstart tests to use the pytest tmp_path fixture rather than creating test directories in the abcclassroom directory (addresses issue #151 ).
> Update quickstart tests for new config options

- CHANGELOG.md
- abcclassroom/config.py
- abcclassroom/example-data/config.yml
- abcclassroom/example-data/readme.md
- abcclassroom/quickstart.py
- abcclassroom/tests/test_assignment_template.py
- abcclassroom/tests/test_quickstart.py
- docs/get-started.rst
This addresses the quickstart bug in #160 (where quickstart is hard-coding the directory names rather than pulling them from the sample config). It also modifies the quickstart code to use the config functions (#142).
> Quickstart bug fixes and improvements

- .travis.yml
should just be a small fix to build off of python 3.8 given we're using it in our classes now.
> add python 3.8 to build

- CHANGELOG.rst
- MANIFEST.in
- abcclassroom/clone.py
- abcclassroom/feedback.py
- abcclassroom/tests/test_clone.py
This addresses #276 . I fixed existing tests but did not add additional ones which is why code cov is unhappy.
seems to be working locally after some testing!! and it's a big improvement. NOTE - docstrings throughout need to be fixed up as we work on things. I also found some flake8 issues which i cleaned up on these files only. 
@nkorinek just a note that given you are working on tests today i just went ahead and implemented this as it's getting messy in my subdirectories for our class!!! we may revisit this pr and add docstrings and such! let's chat about that after you finish up with the tests. 
TODO's
```
repo_name = "{}-{}".format(assignment_name, student)
destination_dir = Path(clone_dir, assignment_name, repo_name)
```
****
i am going to skip tests on this given we are going to …
> Move cloned student directories into assignment subdirectory 

- CHANGELOG.rst
- abcclassroom/__main__.py
- abcclassroom/feedback.py
- abcclassroom/scrub_feedback.py
- docs/api/abcclassroom.rst
- docs/api/abcclassroom.scrub_feedback.rst
- docs/collect-grade-assignments/feedback.rst
This implemented a `--scrub` option on `abc-feedback` which will clean the html files removing hidden tests before pushing to student repos.
It seems to be working as i just used it for assignment 4. no tests added here yet. 
@nkorinek this is the feature that we will add to the PR that you're working on to build out tests. let's coordinate on getting this integrated with your pr when you open it. 
this will have to address #290  #238
> Clean html feedback reports of hidden tests

- CHANGELOG.rst
- abcclassroom/example-data/config.yml
this addresses #297 which makes the default roster name `classroom_roster.csv `which aligns with what github classroom provides upon download.
> make default roster name classroom_roster.csv

- CHANGELOG.rst
- abcclassroom/clone.py
- abcclassroom/github.py
- abcclassroom/quickstart.py
- abcclassroom/tests/conftest.py
- abcclassroom/tests/test_clone.py
fixes #318 
This pr only moves the clone cli function into it's own function so we can also clone directly using python.
There are many TODO's in the clone module.
there are no tests and checks to ensure
1. that the roster exists
2. that the repo exists
3. when clone doesn't work you have no idea why
4. there are no tests really in general of all of the functionality.
i won't work on all of the above now, just am moving things over into a python-ready structure right now.
> Move clone into a stand alone function

- CHANGELOG.rst
- abcclassroom/example-data/config.yml
closes #309 
This is a very minor change to the default config setting for the default template repo directory name. shouldn't impact much but i think it's a better default name.
> rename default template repo dir name

- CHANGELOG.rst
- abcclassroom/clone.py
- abcclassroom/github.py
This fixes a bug where the default branch for the git pull function was still set to `master` rather than `main`. Also added some exception handling, because the failure was silent. 
Closes #376
> Set default branch to main for git pull function

- CHANGELOG.rst
- abcclassroom/__main__.py
- abcclassroom/feedback.py
- abcclassroom/github.py
- abcclassroom/template.py
This creates a new function for checking that ssh keys are set up correctly for use with git commands that talk to github. 
Needs more testing before merge. I have done some local testing, but need to set up a course directory / assignments / students, etc on my local machine for more in-depth checking. If @lwasser or @nkorinek get to this before me - great! The affected abc scripts are: 
* `abc-init`
* `abc-clone`, 
* `abc-new-template` with `--github` option 
* `abc-update-template`
* `abc-feedback` with --github option
There is no pytest coverage, because getting tests that use git with ssh keys to run in Actions is non-trivial (and seems out of scope for this issue, but worth doing, see this milestone https://github.com/earthlab/abc-classroom/milestone/6 ).
Closes #366
> Check ssh git setup

- CHANGELOG.rst
- CONTRIBUTING.rst
- abcclassroom/__main__.py
- abcclassroom/clone.py
- abcclassroom/example-data/classroom_roster.csv
- abcclassroom/example-data/readme.md
- abcclassroom/example-data/sample_roster.csv
- abcclassroom/feedback.py
- abcclassroom/quickstart.py
- abcclassroom/roster.py
- abcclassroom/tests/test_clone.py
- docs/api/abcclassroom.roster.rst
- docs/api/abcclassroom.rst
- docs/get-started/classroom-roster.rst
- docs/get-started/configuration.rst
- docs/get-started/index.rst
- setup.py
Adds a new script, `abc-roster` that creates a nbgrader-formatted roster from a GitHub Classsroom roster. Creates an `id` column from the `github_username` column, and creates `first_name`, `last_name` from `name`. Saves new file as `course_materials/nbgrader_roster.csv`. This addresses #59 (finally!).
Run `abc-roster -h` for usage. 
Also changes code and files to use `classroom_roster.csv` consistently in example files and config, #383 
Also adds better error handing for missing rosters, #384 (noting that I could not reproduce the error in this issue, so I am not 100% sure it it solved).
> Roster management

- .pre-commit-config.yaml
This is just a baby PR that will ensure black - the right version - runs via the pre commit hook. ci was breaking because of this mismatch.
> update pre commit to ensure the right v of black runs

- abcclassroom/auth.py
- abcclassroom/git.py
- abcclassroom/github.py
This is a small PR to wrap up the items in #445 which won't get merged given the restructure. captured all docstring updates here. there is some more work to be done on docstrings throughout abc-classroom ... addresses in part #463
> DOCS: update docstrings on several modules

- CHANGELOG.rst
- docs/manage-assignments/new_assignment.rst
closes #178 
This pr updates the documentation surrounding extra_files and updating the readme. 
We have not merged #471 yet so i want to wait to address docs for that until we have merged it. Perhaps it would make sense to make that change within that open PR?
@kcranston would love you to review the language here to ensure it looks ok.
> start at updating docs for extra_files
