earthlab/abc-classroom

- MANIFEST.in
- README.md
- grading/__main__.py
- grading/circleci.yml
- grading/distribute.py
- grading/github.py
- grading/notebook.py
- grading/ok.py
- grading/utils.py
- master/01-lecture.ipynb
- setup.py
This PR adds some basic tools to generate a template repository for students to fork. The cool thing here is that it generates the configuration needed for CircleCI to run.
The idea for the workflow is:
* teacher generates the student notebooks (`nbauthor` from previous PR)
* teacher generates a student template repo (this PR does that)
* the student template repository contains circlCI settings that will run and grade each notebook in the repository (this PR does that)
* instructor puts the template repo on GitHub
* student's fork the repository
* head to CircleCI.com to activate CI for their fork
* students work on their stuff, look at CircleCI to see how they are doing
> Distributing work

- grading/circleci.yml
Small tweak now that changes are on master.
> Adjust URL in the CircleCI template

- grading/__main__.py
- grading/github.py
We have a token already in our config so lets use that instead of asking people to setup ssh keys.
> Switch to using HTTPS for cloning of repositories

- grading/__main__.py
- grading/circleci.yml
- grading/distribute.py
- grading/github.py
- grading/notebook.py
- grading/utils.py
This adds better support for executing commands from "somwhere" inside
the repository, before you had to run them in the top directory.
This adds support for assignments having the same file name, previously
the rendered notebooks would have the same name and overwrite each
other.
> Handle sub-directories

- grading/__main__.py
- grading/notebook.py
- grading/ok.py
- grading/utils.py
- setup.py
This is the collection of modifications that make an auto grader that can give more than one point per exercise and can have more than one exercise in a cell! 🎉 You heard right.
To make a cell that should be turned into a "test" (checking the students work) you need to tag it with a `public` or `private` tag and put code like the following in it:
```
>>> student_func(3, 4)
12
>>> student_func(3, -4)
-12
>>> student_func(-3, -4)
12
```
this contains two checks. One worth two points, one worth 4 points. The way we split things is by looking for two new lines after each other, aka a blank line. To specify how many points a block is worth write `# POINTS <n>` before the block.
> Autograding

- grading/circleci.yml
Closes #19 
Now when there is a `environment.yml` in the student repository it will be installed and notebooks run in that environment.
> Conda support

- grading/__main__.py
@betatim  another attempt at cleaning up our workflow. Please see what you think. open to any and all edits. I'm wondering still if `authorize()` is deprecated or not. i found a few other github api packages for python but maybe this one is the best. just curious about that. 
this PR addresses [this issue.](https://github.com/earthlab/grading-workflow-experiments/issues/14)
> Fix init fun to check for token before trying to authorize()

- grading/__main__.py
Check if we have a token that is valid and if not refresh it.
Related to #14
> Check for valid token and refresh it when needed

- abcclassroom/__main__.py
Closes #14 
We now store the GitHub token in `~/.abc-classroom.tokens.yml` so that it can be reused across clossrooms and users don't run the risk of accidentally pushing it to GitHub.
> Store GitHub token in user's home directory

- abcclassroom/__main__.py
Added three docstrings, all for functions related to the `init()` function inside of `__main__()`.
> Added docstrings for functions related to abc-init

- docs/conf.py
- setup.cfg
this pr addresses #62 once it's merged i can test deployment to pypi. 
Once that's merged i can address #61
> Add bumpversion setup and fix pytest

- .gitignore
- CHANGELOG.md
- README.md
- docs/api/abcclassroom.config.rst
- docs/api/abcclassroom.distribute.rst
- docs/api/abcclassroom.github.rst
- docs/api/abcclassroom.notebook.rst
- docs/api/abcclassroom.ok.rst
- docs/api/abcclassroom.quickstart.rst
- docs/api/abcclassroom.rst
- docs/api/abcclassroom.template.rst
- docs/api/abcclassroom.utils.rst
- readthedocs.yml
The docs have been failing for 2 weeks now. i suspect it's a setup issue but will see if this fixes things. 
fixes
This should address #114  #113
> Add docs badge to readme and RTD Config

- docs/get-started.rst
- docs/new_assignment.rst
Working through the entire process again!
> minor tweaks to docs

- bandit.yml
addresses issue #158
PR #157 should be merged first (and then master will need to be merged here)
> add bandit config to suppress assert errors

- CHANGELOG.md
- abcclassroom/__main__.py
Fixes #163 (need to issue new release so that version of pip has same behaviour as local install)
> add external file prefix to set_github_auth

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.rst
- abcclassroom/__main__.py
- docs/abc-overview.rst
- docs/api/abcclassroom.feedback.rst
- docs/api/abcclassroom.rst
- docs/clone.rst
- docs/configuration.rst
- docs/course-materials.rst
- docs/feedback.rst
- docs/get-started.rst
- docs/index.rst
- docs/new_assignment.rst
- docs/overview.rst
- docs/previous-functionality.rst
Opening this early in case it is helpful for @jlpalomino to see what I am working on. I'll modify the title to remove the [WIP] when it is ready for merge.
> Refactor docs

- CHANGELOG.md
- abcclassroom/__main__.py
- abcclassroom/feedback.py
fixes bug reported by @jlpalomino on slack
> Feedback fix

- .pre-commit-config.yaml
- abcclassroom/clone.py
- tox.ini
this pr adds flake 8
what we could do is add the infrastructure and the pre-commit. that way we will be forced to format the files we are working on but we won't be bothered by CI just yet. we can uncomment the line to run in CI once we have more of the repo fixed! 
this will allow us to gradually migrate to flake8 standards without having to do it all at once!
> Add flake 8

- .pre-commit-config.yaml
- CHANGELOG.md
- abcclassroom/__main__.py
- abcclassroom/config.py
- abcclassroom/example-data/config.yml
- abcclassroom/example-data/extra_files/.gitignore
- abcclassroom/example-data/extra_files/readme.md
- abcclassroom/example-data/readme.md
- abcclassroom/github.py
- abcclassroom/ok.py
- abcclassroom/quickstart.py
- abcclassroom/template.py
- abcclassroom/tests/conftest.py
- abcclassroom/tests/test_assignment_template.py
- abcclassroom/tests/test_quickstart.py
- abcclassroom/utils.py
- docs/api/abcclassroom.rst
- docs/course-materials.rst
- docs/get-started.rst
- docs/new_assignment.rst
so i could merge this - this is a new branch merged with master locally to resolve conflicts. this addresses #203 extra files. it seems to be working well locally.
> Extra files - #203 replacement

- .zenodo.json
Added a zenodo file with all the contributors listed in this issue: https://github.com/earthlab/abc-classroom/issues/252
> Added the zenodo file with the contributors

- CHANGELOG.rst
- MANIFEST.in
addresses #272 
Essentially the data weren't packaged correctly previously. this will fix that issue!! tested locally and it bundled up perfectly.
> update manifest to package example-data directory

- .github/workflows/windows-python-package.yml
- CHANGELOG.rst
Testing github actions for windows. it seems to work. i may remove linting at some point #300
> Use GH actions for windows tests

- .travis.yml
- .travis/install.sh
- .travis/test.sh
- environment_osx.yml
- tox.ini
fixes #313 
i have no idea how this has actually been running
OK IT'S DEF installing python 3.9
https://travis-ci.com/github/earthlab/abc-classroom/jobs/403369729#L359
> fix ci inconsistencies

- docs/collect-grade-assignments/clone.rst
- docs/manage-assignments/create-grade-assignment-workflow.rst
- docs/manage-assignments/new_assignment.rst
This just helps me (and the user) understand how to change permissions on that .rsa file on a  jupyter hub. note it still needs to be run every few days to work.
> Doc update for permissions on the jhub

- dev-requirements.txt
Consolidated dependency updates
> consolidated dependancy updates

- .github/workflows/code-cov.yml
Making sure code cov runs on every pr opened in this repo. Quick and small fix.
> Code Cov Update

- CHANGELOG.rst
- abcclassroom/quickstart.py
> fix quickstart success message

- CHANGELOG.rst
> update changelog for last two PRs

- CHANGELOG.rst
- abcclassroom/git.py
> remove one more unused function

- abcclassroom/__main__.py
These were introduced when these two commits missed updating __main__.py
8a9ab65cce652cf22c3785e6bde9809c23d45f90
e99472705a3fc9dcd2c80e95b5be58d02d4a9898
Cc: @kcranston (thanks for your work; just noticed these issues)
> Fix imports for abc-init

- docs/get-started/get-started.rst
> Updated docs with conda-forge instructions

- CHANGELOG.rst
- abcclassroom/__main__.py
- abcclassroom/auth.py
Addresses #460 
We can either review and merge #459 first and then fix conflicts here or merge this first and update #459. This PR will probably make test organization simpler.
> Reorganize checking and generation of github api access token

- .github/workflows/run-tests-mac-win-linux.yml
- dev-requirements.txt
doing it in a new pr to make it clean, closes https://github.com/earthlab/abc-classroom/pull/479
> Updating pydata in main and removing support for 3.6

- .github/workflows/code-cov.yml
- .github/workflows/run-tests-mac-win-linux.yml
- .pre-commit-config.yaml
- dev-requirements.txt
- docs/conf.py
- readthedocs.yml
Updating dependencies and upgrading to python 3.10
> Dependency updates
